# -*- coding: utf-8 -*-
"""pencil_to_sketch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ndfy8nBuKLNddBW3wouyZt4I-cze-1VO
"""

# import the library
import cv2
import matplotlib.pyplot as plt

# read the image
img_file = 'pexels-frank-cone-2629372.jpg'
original_image = cv2.imread(img_file)

# conver the image to rgb
original_img_rgb = cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB)

#convert the image to gray scale
gray_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)

# inver the grayscale image
inverted_grey_image = cv2.bitwise_not(gray_image)

# blur the inverted gray image using gaussian blur image
blurred_image = cv2.GaussianBlur(inverted_grey_image, (111, 111), 0)

# inver the GaussianBlur image
inverted_blurred_image = cv2.bitwise_not(blurred_image)

# create the pencil sketch
pencil_sketch = cv2.divide(gray_image, inverted_blurred_image, scale = 256.0)

#convert the image into gray
pencil_sketch_gray = cv2.cvtColor(pencil_sketch, cv2.COLOR_GRAY2RGB)

# display the pencil sketch
plt.imshow(pencil_sketch_gray)
plt.axis('off')
plt.title('Pencil Sketch')
plt.show()